
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.stone_type]

		[types.stone_type.pasterdream]
			shadow_stone = true
			cyan_stone = true

		[types.stone_type.biomesoplenty]
			brimstone = true

		[types.stone_type.ad_astra]
			moon_stone = true
			mars_stone = true
			mercury_stone = true
			venus_stone = true
			venus_sandstone = true
			glacio_stone = true
			permafrost = true

		[types.stone_type.blue_skies]
			polished_brumble = true

		[types.stone_type.aether]
			holystone = true

		[types.stone_type.gravitation]
			conglomerate = true

		[types.stone_type.deep_aether]
			aseterite = true
			aether_mud = true

		[types.stone_type.aether_redux]
			sentrite = true

		[types.stone_type.naturalist]
			shellstone = true

		[types.stone_type.create]
			cut_granite = true
			cut_diorite = true
			cut_andesite = true
			cut_calcite = true
			cut_dripstone = true
			cut_deepslate = true
			cut_tuff = true
			cut_asurine = true
			cut_crimsite = true
			cut_limestone = true
			cut_ochrum = true
			cut_scoria = true
			cut_scorchia = true
			cut_veridium = true

		[types.stone_type.upgrade_aquatic]
			kelpy_cobblestone = true

		[types.stone_type.alexscaves]
			galena = true
			radrock = true
			abyssmarine = true
			guanostone = true

		[types.stone_type.forbidden_arcanus]
			polished_darkstone = true

		[types.stone_type.astral_dimension]
			astral_stone = true
			harsh_stone = true
			astral_marble = true
			moonstone = true
			pyrite = true

	[types.wood_type]

		[types.wood_type.domum_ornamentum]
			cactus = true
			cactus_extra = true

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.blue_skies]
			crystallized = true
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			comet = true

		[types.wood_type.naturesaura]
			ancient = true

		[types.wood_type.pasterdream]
			dyedream = true
			shadow = true
			windmoor = true

		[types.wood_type.biomesoplenty]
			fir = true
			pine = true
			maple = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true
			empyreal = true

		[types.wood_type.ad_astra]
			aeronos = true
			strophar = true
			glacian = true

		[types.wood_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.wood_type.aether]
			skyroot = true

		[types.wood_type.gravitation]
			aerfin = true
			beladon = true
			enchanted = true

		[types.wood_type.deep_aether]
			roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.wood_type.aether_redux]
			fieldsproot = true
			blightwillow = true
			cloudcap = true
			jellyshroom = true
			crystal = true
			glacia = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.beachparty]
			palm = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.forbidden_arcanus]
			fungyss = true
			aurum = true
			edelwood = true

		[types.wood_type.betterarcheology]
			rotten = true

		[types.wood_type.astral_dimension]
			luminous = true
			tormented = true
			soggy = true
			wisteria = true

	[types.leaves_type]

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			red_maple = true
			orange_maple = true
			yellow_maple = true
			rainbow_birch = true
			snowblossom = true
			null = true
			cypress = true
			fir = true
			pine = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true
			empyreal = true

		[types.leaves_type.blue_skies]
			crystallized = true
			crescent_fruit = true
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			comet = true

		[types.leaves_type.twilightforest]
			beanstalk = true
			thorn = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.naturesaura]
			ancient = true
			golden = true

		[types.leaves_type.pasterdream]
			dyedream = true

		[types.leaves_type.ad_astra]
			glacian = true

		[types.leaves_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.leaves_type.aether]
			skyroot = true
			golden_oak = true
			crystal = true
			crystal_fruit = true
			holiday = true
			decorated_holiday = true

		[types.leaves_type.gravitation]
			aerfin = true
			blue_aerfin = true
			golden_aerfin = true
			beladon = true
			enchanted = true

		[types.leaves_type.deep_aether]
			roseroot = true
			flowering_roseroot = true
			blue_roseroot = true
			flowering_blue_roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.leaves_type.aether_redux]
			blightwillow = true
			glacia = true
			purple_glacia = true
			gilded_oak = true
			blighted_skyroot = true

		[types.leaves_type.twilightdelight]
			ironwood = true

		[types.leaves_type.beachparty]
			palm = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.forbidden_arcanus]
			aurum = true
			nuggety_aurum = true

		[types.leaves_type.astral_dimension]
			fiery = true
			soggy = true
			wisteria = true
			fiery_birch = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.boatload]
			large_boat = true
			furnace_boat = true

		[entries.wood_type.mcwfurnitures]
			wardrobe = true
			stripped_glass_table = true
			stripped_desk = true
			modern_desk = true
			stripped_lower_bookshelf_drawer = true
			stripped_end_table = true
			end_table = true
			stool_chair = true
			drawer = true
			stripped_lower_triple_drawer = true
			stripped_bookshelf_drawer = true
			stripped_bookshelf = true
			modern_chair = true
			stripped_drawer_counter = true
			bookshelf_drawer = true
			chair = true
			stripped_table = true
			double_drawer = true
			stripped_coffee_table = true
			stripped_counter = true
			double_drawer_counter = true
			stripped_striped_chair = true
			covered_desk = true
			drawer_counter = true
			counter = true
			stripped_modern_chair = true
			bookshelf_cupboard = true
			table = true
			stripped_stool_chair = true
			stripped_modern_wardrobe = true
			cupboard_counter = true
			desk = true
			stripped_covered_desk = true
			coffee_table = true
			glass_table = true
			stripped_double_wardrobe = true
			stripped_cupboard_counter = true
			stripped_triple_drawer = true
			stripped_chair = true
			stripped_double_drawer = true
			stripped_double_drawer_counter = true
			triple_drawer = true
			lower_triple_drawer = true
			bookshelf = true
			stripped_wardrobe = true
			large_drawer = true
			stripped_modern_desk = true
			stripped_bookshelf_cupboard = true
			modern_wardrobe = true
			double_wardrobe = true
			stripped_drawer = true
			lower_bookshelf_drawer = true
			striped_chair = true
			stripped_large_drawer = true

		[entries.wood_type.another_furniture]
			shelf = true
			bench = true
			flower_box = true
			shutter = true
			table = true
			drawer = true
			chair = true

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.twilightforest]
			banister = true
			hollow_log_climbable = true
			hollow_log_horizontal = true
			hollow_log_vertical = true

		[entries.wood_type.farmersdelight]
			cabinet = true

