#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Fri Jul 04 06:06:22 EDT 2025
another_furniture=true
boatload=true
create=true
decorative_blocks=true
farmersdelight=true
mcwfurnitures=true
twilightforest=true
